/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUploadRouteImport } from './routes/app.upload'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppMyCertificatesRouteImport } from './routes/app.my-certificates'
import { Route as AppMasterDataRouteImport } from './routes/app.master-data'
import { Route as AppFormsRouteImport } from './routes/app.forms'
import { Route as AppCertificatesRouteImport } from './routes/app.certificates'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppMasterDataIndexRouteImport } from './routes/app.master-data.index'
import { Route as AppMasterDataDomainsRouteImport } from './routes/app.master-data.domains'
import { Route as AppMasterDataCohortsRouteImport } from './routes/app.master-data.cohorts'
import { Route as AppMasterDataModuleRouteImport } from './routes/app.master-data.$module'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppMyCertificatesRoute = AppMyCertificatesRouteImport.update({
  id: '/my-certificates',
  path: '/my-certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterDataRoute = AppMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterDataIndexRoute = AppMasterDataIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMasterDataRoute,
} as any)
const AppMasterDataDomainsRoute = AppMasterDataDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppMasterDataRoute,
} as any)
const AppMasterDataCohortsRoute = AppMasterDataCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => AppMasterDataRoute,
} as any)
const AppMasterDataModuleRoute = AppMasterDataModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AppMasterDataRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/audit': typeof AppAuditRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/forms': typeof AppFormsRoute
  '/app/master-data': typeof AppMasterDataRouteWithChildren
  '/app/my-certificates': typeof AppMyCertificatesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/upload': typeof AppUploadRoute
  '/app/': typeof AppIndexRoute
  '/app/master-data/$module': typeof AppMasterDataModuleRoute
  '/app/master-data/cohorts': typeof AppMasterDataCohortsRoute
  '/app/master-data/domains': typeof AppMasterDataDomainsRoute
  '/app/master-data/': typeof AppMasterDataIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/audit': typeof AppAuditRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/forms': typeof AppFormsRoute
  '/app/my-certificates': typeof AppMyCertificatesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/upload': typeof AppUploadRoute
  '/app': typeof AppIndexRoute
  '/app/master-data/$module': typeof AppMasterDataModuleRoute
  '/app/master-data/cohorts': typeof AppMasterDataCohortsRoute
  '/app/master-data/domains': typeof AppMasterDataDomainsRoute
  '/app/master-data': typeof AppMasterDataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/audit': typeof AppAuditRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/forms': typeof AppFormsRoute
  '/app/master-data': typeof AppMasterDataRouteWithChildren
  '/app/my-certificates': typeof AppMyCertificatesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/upload': typeof AppUploadRoute
  '/app/': typeof AppIndexRoute
  '/app/master-data/$module': typeof AppMasterDataModuleRoute
  '/app/master-data/cohorts': typeof AppMasterDataCohortsRoute
  '/app/master-data/domains': typeof AppMasterDataDomainsRoute
  '/app/master-data/': typeof AppMasterDataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/audit'
    | '/app/certificates'
    | '/app/forms'
    | '/app/master-data'
    | '/app/my-certificates'
    | '/app/reports'
    | '/app/roles'
    | '/app/settings'
    | '/app/students'
    | '/app/upload'
    | '/app/'
    | '/app/master-data/$module'
    | '/app/master-data/cohorts'
    | '/app/master-data/domains'
    | '/app/master-data/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/audit'
    | '/app/certificates'
    | '/app/forms'
    | '/app/my-certificates'
    | '/app/reports'
    | '/app/roles'
    | '/app/settings'
    | '/app/students'
    | '/app/upload'
    | '/app'
    | '/app/master-data/$module'
    | '/app/master-data/cohorts'
    | '/app/master-data/domains'
    | '/app/master-data'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/audit'
    | '/app/certificates'
    | '/app/forms'
    | '/app/master-data'
    | '/app/my-certificates'
    | '/app/reports'
    | '/app/roles'
    | '/app/settings'
    | '/app/students'
    | '/app/upload'
    | '/app/'
    | '/app/master-data/$module'
    | '/app/master-data/cohorts'
    | '/app/master-data/domains'
    | '/app/master-data/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-certificates': {
      id: '/app/my-certificates'
      path: '/my-certificates'
      fullPath: '/app/my-certificates'
      preLoaderRoute: typeof AppMyCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/master-data': {
      id: '/app/master-data'
      path: '/master-data'
      fullPath: '/app/master-data'
      preLoaderRoute: typeof AppMasterDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forms': {
      id: '/app/forms'
      path: '/forms'
      fullPath: '/app/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates': {
      id: '/app/certificates'
      path: '/certificates'
      fullPath: '/app/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/master-data/': {
      id: '/app/master-data/'
      path: '/'
      fullPath: '/app/master-data/'
      preLoaderRoute: typeof AppMasterDataIndexRouteImport
      parentRoute: typeof AppMasterDataRoute
    }
    '/app/master-data/domains': {
      id: '/app/master-data/domains'
      path: '/domains'
      fullPath: '/app/master-data/domains'
      preLoaderRoute: typeof AppMasterDataDomainsRouteImport
      parentRoute: typeof AppMasterDataRoute
    }
    '/app/master-data/cohorts': {
      id: '/app/master-data/cohorts'
      path: '/cohorts'
      fullPath: '/app/master-data/cohorts'
      preLoaderRoute: typeof AppMasterDataCohortsRouteImport
      parentRoute: typeof AppMasterDataRoute
    }
    '/app/master-data/$module': {
      id: '/app/master-data/$module'
      path: '/$module'
      fullPath: '/app/master-data/$module'
      preLoaderRoute: typeof AppMasterDataModuleRouteImport
      parentRoute: typeof AppMasterDataRoute
    }
  }
}

interface AppMasterDataRouteChildren {
  AppMasterDataModuleRoute: typeof AppMasterDataModuleRoute
  AppMasterDataCohortsRoute: typeof AppMasterDataCohortsRoute
  AppMasterDataDomainsRoute: typeof AppMasterDataDomainsRoute
  AppMasterDataIndexRoute: typeof AppMasterDataIndexRoute
}

const AppMasterDataRouteChildren: AppMasterDataRouteChildren = {
  AppMasterDataModuleRoute: AppMasterDataModuleRoute,
  AppMasterDataCohortsRoute: AppMasterDataCohortsRoute,
  AppMasterDataDomainsRoute: AppMasterDataDomainsRoute,
  AppMasterDataIndexRoute: AppMasterDataIndexRoute,
}

const AppMasterDataRouteWithChildren = AppMasterDataRoute._addFileChildren(
  AppMasterDataRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppFormsRoute: typeof AppFormsRoute
  AppMasterDataRoute: typeof AppMasterDataRouteWithChildren
  AppMyCertificatesRoute: typeof AppMyCertificatesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppFormsRoute: AppFormsRoute,
  AppMasterDataRoute: AppMasterDataRouteWithChildren,
  AppMyCertificatesRoute: AppMyCertificatesRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
